#!/bin/sh /etc/rc.common
# Copyright (C) 2020 IrineSistiana

START=99
USE_PROCD=1
#PROCD_DEBUG=1

#####  ONLY CHANGE THIS BLOCK  ######
PROG=/usr/bin/mos-chinadns  # where is mos-chinadns
RES_DIR=/etc/mos-chinadns/  # resource dir / working dir / the dir where you store ip/domain lists
CONF=./config.json          # where is the config file
#####  ONLY CHANGE THIS BLOCK  ######

start_service() {
	procd_open_instance
	procd_set_param command $PROG -dir $RES_DIR -c $CONF -quiet

	procd_set_param user root
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
	echo "mos-chinadns is started!"
}

reload_service() {
	stop
	sleep 2s
	echo "mos-chinadns is restarted!"
	start
}